import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatDate(date) {
  return new Date(date).toLocaleString();
}

function addSection(doc, title, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(title, 14, y);

  doc.setDrawColor(220);
  doc.line(14, y + 3, 196, y + 3);

  return y + 10;
}

export function exportReviewAsPDF(review) {
  const doc = new jsPDF();

  let y = 18;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("CThru", 14, y);

  y += 8;

  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("AI Code Review Report", 14, y);

  y += 14;

  // Review Details
  y = addSection(doc, "Review Details", y);

  autoTable(doc, {
    startY: y,
    theme: "grid",
    styles: {
      fontSize: 10,
    },
    body: [
      ["Project", review.title],
      ["Language", review.language],
      ["Generated", formatDate(review.createdAt)],
      ["Overall Score", `${review.overallScore ?? 0}/100`],
    ],
  });

  y = doc.lastAutoTable.finalY + 12;

  // Scores
  const scores = review.metrics?.categoryScores || {};

  y = addSection(doc, "Category Scores", y);

  autoTable(doc, {
    startY: y,
    theme: "striped",
    head: [["Category", "Score"]],
    body: [
      ["Security", scores.Security ?? "-"],
      ["Code Quality", scores["Code Quality"] ?? "-"],
      ["Complexity", scores.Complexity ?? "-"],
    ],
  });

  y = doc.lastAutoTable.finalY + 12;

  // Summary
  if (review.summary) {
    y = addSection(doc, "AI Summary", y);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const text = doc.splitTextToSize(review.summary, 180);

    doc.text(text, 14, y);

    y += text.length * 6 + 10;
  }

  // Metrics
  const metrics = review.metrics || {};

  y = addSection(doc, "Metrics", y);

  autoTable(doc, {
    startY: y,
    theme: "grid",
    body: [
      ["Lines of Code", metrics.linesOfCode ?? "-"],
      ["Functions", metrics.functionCount ?? "-"],
      ["Classes", metrics.classCount ?? "-"],
      ["Cyclomatic Complexity", metrics.cyclomaticComplexity ?? "-"],
    ],
  });

  y = doc.lastAutoTable.finalY + 12;

  // Findings
  y = addSection(doc, "Findings", y);

  const findings =
    review.findings?.map((finding) => [
      finding.severity.toUpperCase(),
      finding.category,
      finding.issue,
      finding.suggestedFix,
    ]) || [];

  autoTable(doc, {
    startY: y,
    head: [["Severity", "Category", "Issue", "Suggested Fix"]],
    body: findings.length ? findings : [["-", "-", "No findings", "-"]],
    styles: {
      fontSize: 9,
      cellWidth: "wrap",
    },
  });

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(9);

  doc.setTextColor(120);

  doc.text("Generated by CThru", 14, pageHeight - 10);

  doc.save(`${review.title}.pdf`);
}
