import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatDate(date) {
  if (!date) return "N/A";
  return new Date(date).toLocaleDateString("en-US", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// Global drawing helpers for layout & safety
function ensureSpace(doc, requiredHeight, margin = 14) {
  const pageHeight = doc.internal.pageSize.height;
  if (doc.currentY + requiredHeight > pageHeight - margin) {
    doc.addPage();
    doc.currentY = margin + 15; // Reset Y with top padding
    return true;
  }
  return false;
}

function drawFooter(doc) {
  const totalPages = doc.internal.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128); // #6B7280 Gray

    // Divider line
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.line(14, pageHeight - 16, 196, pageHeight - 16);

    // Left & Right Footer Text
    doc.text("Generated by CThru", 14, pageHeight - 10);
    doc.text(`Page ${i} of ${totalPages}`, 196, pageHeight - 10, {
      align: "right",
    });
  }
}

export function exportReviewAsPDF(review) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Palette definitions
  const colors = {
    primary: [79, 70, 229], // #4F46E5 Indigo
    success: [34, 197, 94], // #22C55E Green
    warning: [245, 158, 11], // #F59E0B Yellow
    critical: [239, 68, 68], // #EF4444 Red
    gray: [107, 114, 128], // #6B7280 Gray
    textDark: [15, 23, 42], // #0F172A Dark Slate
    bgLight: [249, 250, 251], // #F9FAFB Card Background
  };

  doc.currentY = 20;

  // ==========================================
  // PAGE 1: HEADER BLOCK & LAYOUT
  // ==========================================

  // 1. Top Branding Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.text("CThru", 14, doc.currentY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
  doc.text("AI Code Review Report", 196, doc.currentY, { align: "right" });
  doc.text(
    `Generated: ${formatDate(review.createdAt)}`,
    196,
    doc.currentY + 5,
    { align: "right" },
  );

  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(14, doc.currentY + 9, 196, doc.currentY + 9);

  doc.currentY += 22;

  // 2. Project Identification Meta
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(colors.textDark[0], colors.textDark[1], colors.textDark[2]);
  doc.text(String(review.title || "javascript Review"), 14, doc.currentY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
  doc.text("Language", 14, doc.currentY + 10);
  doc.text("Analysis Type", 14, doc.currentY + 16);
  doc.text("Date", 14, doc.currentY + 22);

  doc.setTextColor(colors.textDark[0], colors.textDark[1], colors.textDark[2]);
  doc.text(String(review.language || "JavaScript"), 45, doc.currentY + 10);
  doc.text("AI + Static Analysis", 45, doc.currentY + 16);
  doc.text(formatDate(review.createdAt), 45, doc.currentY + 22);

  // 3. Score Badge Vector Component
  const score = review.overallScore ?? 0;
  let badgeColor = colors.critical;
  let badgeLabel = "POOR";

  if (score >= 90) {
    badgeColor = colors.success;
    badgeLabel = "EXCELLENT";
  } else if (score >= 70) {
    badgeColor = colors.warning;
    badgeLabel = "GOOD";
  }

  // Draw Score Badge Box Container
  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(146, doc.currentY + 2, 50, 24, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(badgeColor[0], badgeColor[1], badgeColor[2]);
  doc.text(String(score), 171, doc.currentY + 11, { align: "center" });

  doc.setFontSize(9.5);
  doc.text(badgeLabel, 171, doc.currentY + 19, { align: "center" });

  doc.currentY += 38;

  // 4. Corrected AI Summary Handling
  let rawSummary = review.aiSummary || review.summary || "";

  if (rawSummary.trim().startsWith("{")) {
    try {
      const parsed = JSON.parse(rawSummary);
      rawSummary = parsed.aiSummary || parsed.summary || rawSummary;
    } catch (e) {}
  }

  if (rawSummary) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(
      colors.textDark[0],
      colors.textDark[1],
      colors.textDark[2],
    );
    doc.text("AI Summary", 14, doc.currentY);

    doc.setDrawColor(229, 231, 235);
    doc.line(14, doc.currentY + 2, 196, doc.currentY + 2);
    doc.currentY += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(
      colors.textDark[0],
      colors.textDark[1],
      colors.textDark[2],
    );

    const splitSummary = doc.splitTextToSize(rawSummary, 182);
    doc.text(splitSummary, 14, doc.currentY, {
      maxWidth: 182,
      lineHeightFactor: 1.4,
    });

    doc.currentY += splitSummary.length * 6 + 16;
  }

  // 5. Category Progress Bars
  ensureSpace(doc, 50);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(colors.textDark[0], colors.textDark[1], colors.textDark[2]);
  doc.text("Category Scores", 14, doc.currentY);
  doc.setDrawColor(229, 231, 235);
  doc.line(14, doc.currentY + 2, 196, doc.currentY + 2);
  doc.currentY += 12;

  const metricsObj = review.metrics || {};
  const scores = metricsObj.categoryScores || {};
  const categories = [
    { label: "Security", val: scores.Security ?? 100 },
    { label: "Code Quality", val: scores["Code Quality"] ?? 89 },
    { label: "Complexity", val: scores.Complexity ?? 100 },
  ];

  categories.forEach((cat) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(
      colors.textDark[0],
      colors.textDark[1],
      colors.textDark[2],
    );
    doc.text(cat.label, 14, doc.currentY + 4);

    const trackWidth = 100;
    const fillWidth = (cat.val / 100) * trackWidth;

    doc.setFillColor(243, 244, 246);
    doc.roundedRect(60, doc.currentY, trackWidth, 5, 1, 1, "F");

    let barColor = colors.primary;
    if (cat.val >= 90) barColor = colors.success;
    else if (cat.val >= 70) barColor = colors.warning;
    else barColor = colors.critical;

    doc.setFillColor(barColor[0], barColor[1], barColor[2]);
    doc.roundedRect(60, doc.currentY, fillWidth, 5, 1, 1, "F");

    doc.setFont("helvetica", "bold");
    doc.text(String(cat.val), 168, doc.currentY + 4);

    doc.currentY += 12; // Increased line gap step to fully clear bars
  });

  doc.currentY += 8; // Extra padding layout buffer spacing

  // 6. Quick Metrics Layout Components Cards Grid
  ensureSpace(doc, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(colors.textDark[0], colors.textDark[1], colors.textDark[2]);
  doc.text("Quick Metrics", 14, doc.currentY);
  doc.setDrawColor(229, 231, 235);
  doc.line(14, doc.currentY + 2, 196, doc.currentY + 2);
  doc.currentY += 12; // Increased padding after the section line

  const quickMetrics = [
    { title: "LOC", val: metricsObj.codeLines ?? metricsObj.linesOfCode ?? 7 },
    { title: "Complexity", val: metricsObj.complexity ?? 2 },
    {
      title: "Issues",
      val: metricsObj.uniqueIssueCount ?? review.findings?.length ?? 3,
    },
    { title: "Blank Lines", val: metricsObj.blankLines ?? 2 },
  ];

  const cardWidth = 42;
  const cardHeight = 18;
  const gap = 4.5;

  quickMetrics.forEach((metric, index) => {
    const cardX = 14 + index * (cardWidth + gap);
    doc.setFillColor(colors.bgLight[0], colors.bgLight[1], colors.bgLight[2]);
    doc.setDrawColor(229, 231, 235);
    doc.roundedRect(cardX, doc.currentY, cardWidth, cardHeight, 1.5, 1.5, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
    doc.text(metric.title, cardX + 4, doc.currentY + 5.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(
      colors.textDark[0],
      colors.textDark[1],
      colors.textDark[2],
    );
    doc.text(String(metric.val), cardX + 4, doc.currentY + 13);
  });

  // ==========================================
  // PAGE 2+: DETAILED BLOCK COMPONENT FINDINGS
  // ==========================================
  doc.addPage();
  doc.currentY = 25;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(colors.textDark[0], colors.textDark[1], colors.textDark[2]);
  doc.text("Findings", 14, doc.currentY);
  doc.setDrawColor(229, 231, 235);
  doc.line(14, doc.currentY + 2, 196, doc.currentY + 2);
  doc.currentY += 12;

  const findings = review.findings || [];

  if (findings.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
    doc.text("Clean build. No active systemic issues found.", 14, doc.currentY);
  } else {
    findings.forEach((finding) => {
      const severity = (finding.severity || "LOW").toUpperCase();
      let themeColor = colors.gray;

      if (severity === "CRITICAL" || severity === "HIGH") {
        themeColor = colors.critical;
      } else if (severity === "MEDIUM") {
        themeColor = colors.warning;
      } else if (severity === "LOW") {
        themeColor = [59, 130, 246]; // Blue
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      const splitExplanation = doc.splitTextToSize(
        finding.explanation || finding.issue || "",
        182,
      );
      const splitFix = doc.splitTextToSize(
        finding.suggestedFix || "No remediation suggested.",
        174,
      );

      const totalBlockHeight =
        6 +
        8 +
        6 +
        splitExplanation.length * 5.5 +
        8 +
        splitFix.length * 5.5 +
        6 +
        12;

      ensureSpace(doc, totalBlockHeight);

      // A. Render Pill Alert Segment (FIXED: Native vector circle + dynamic spacing)
      doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
      doc.circle(16, doc.currentY - 1.2, 1.5, "F"); // Draws a perfect crisp dot

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
      doc.text(severity, 20, doc.currentY);

      // Calculate exactly how wide the severity text is dynamically
      const severityWidth = doc.getTextWidth(severity);

      const linesLabel = finding.lineNumbers?.length
        ? `Line ${finding.lineNumbers.join(", ")}`
        : "General Context";
      doc.setFont("helvetica", "normal");
      doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
      // Position the next string exactly after the dynamic text width
      doc.text(
        ` |  ${finding.category || "Code Quality"} (${linesLabel})`,
        20 + severityWidth + 2,
        doc.currentY,
      );
      doc.currentY += 7;

      // B. Display Summary Issue Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(
        colors.textDark[0],
        colors.textDark[1],
        colors.textDark[2],
      );
      doc.text(finding.issue || "Issue Block Summary", 14, doc.currentY);
      doc.currentY += 7;

      // C. Render Detailed Explanation Block
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
      doc.text("Explanation", 14, doc.currentY);
      doc.currentY += 4.5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(
        colors.textDark[0],
        colors.textDark[1],
        colors.textDark[2],
      );
      doc.text(splitExplanation, 14, doc.currentY, { lineHeightFactor: 1.3 });
      doc.currentY += splitExplanation.length * 5.5 + 5;

      // D. Draw Fix Recommendations Container Card
      if (finding.suggestedFix) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(
          colors.primary[0],
          colors.primary[1],
          colors.primary[2],
        );
        doc.text("Suggested Fix", 14, doc.currentY);
        doc.currentY += 3;

        const boxH = splitFix.length * 5.5 + 6;
        doc.setFillColor(245, 246, 255);
        doc.setDrawColor(224, 231, 255);
        doc.roundedRect(14, doc.currentY, 182, boxH, 1, 1, "FD");

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(49, 46, 129);
        doc.text(splitFix, 18, doc.currentY + 5.5, { lineHeightFactor: 1.3 });

        doc.currentY += boxH + 8;
      }

      // E. Bottom Section Border Segment
      doc.setDrawColor(243, 244, 246);
      doc.setLineWidth(0.5);
      doc.line(14, doc.currentY, 196, doc.currentY);
      doc.currentY += 10;
    });
  }

  drawFooter(doc);

  doc.save(
    `CThru-Report-${(review.title || "Review").replace(/\s+/g, "_")}.pdf`,
  );
}
